const assert = require("assert");
const fs = require("fs");
const path = require("path");
const pkg = JSON.parse(fs.readFileSync(path.join(__dirname, "..", "package.json"), "utf8"));
const ioPkg = JSON.parse(fs.readFileSync(path.join(__dirname, "..", "io-package.json"), "utf8"));
const main = fs.readFileSync(path.join(__dirname, "..", "main.js"), "utf8");
assert.strictEqual(pkg.name, "iobroker.mcz-maestro");
assert.strictEqual(pkg.version, "0.3.3");
assert.strictEqual(pkg.author, "dataeasy");
assert.strictEqual(ioPkg.common.version, "0.3.3");
assert.ok(main.includes('if(leaf==="powerOn")'));
assert.ok(main.includes('if(leaf==="powerOff")'));
assert.ok(main.includes('COMMANDS.power,true'));
assert.ok(!main.includes('COMMANDS.power,40'));
assert.ok(main.includes('const isButton=role==="button"'));
console.log("Offline unit checks passed.");
